### ISSUE TITLE
Community maintenance

### ISSUE THREAD

**Issue by Pathoschild** [lambui/StardewValleyMod_TractorMod#4]
Hi! You suggested I take over the mod in #3. Would you be interested in [community maintenance](https://github.com/Pathoschild/StardewCommunityMods#faqs) instead?

If you're interested, you just need to [choose an open-source license](https://choosealicense.com/). You can reply with the one you like, and I'll submit a pull request to add the `LICENSE` file. If you're not sure, the [MIT license](https://choosealicense.com/licenses/mit/) is a good simple one.

It would be useful if you could add me as a maintainer in this repository too, though that's not required.

**Comment by lambui** [comment]
I want this proj to continue being developed and maintained by the community. I have added the MIT license.

I also add you as a collaborator of this repo so now you can start releasing the built updates. I really appreciate your help :)

**Comment by Pathoschild** [comment]
Thanks! The usual next steps for community maintenance would be:

1. I'll merge the mod code (with commit history) into the [StardewCommunityMods](https://github.com/Pathoschild/StardewCommunityMods) repository.  
   _Each mod in that repository has its own license. Having everything in one repository makes them easier to update together for SMAPI and game updates. You're welcome to merge changes back into this repository if you'd like._
2. I'll create a Nexus page for the mod.  
   _This page will give you full credit as the original author. If you have a Nexus account, I can add you as a mod owner too._
3. I'll release updates to the Nexus page, and continue posting update announcements to the [forum thread you created](http://community.playstarbound.com/threads/gameplay-mod-tractor-mod.126955).

Does that sound good to you? I don't want to do anything you're uncomfortable with. :)

**Comment by Pathoschild** [comment]
I adopted Tractor Mod (with full credit to lambui as the original author); see the [Nexus page](https://www.nexusmods.com/stardewvalley/mods/1401) for the latest updates.
