### ISSUE TITLE
Using tractor with hoe destroys already placed objects

### ISSUE THREAD

**Issue by absolyst** [lambui/StardewValleyMod_TractorMod#5]
Hey, sorry if this isn't the right place to talk about issues with the mod, but I just wanted to point out that whenever I start tilling dirt with the tractor, it destroys any objects that would normally just be hoed out of the ground if I were just using the hoe by itself. Sprinklers, scarecrows, lampposts, etc., all get irretrievably destroyed if they're in the radius of the tractor while I'm using it to till dirt. Just wanted to raise that issue, thanks.

**Comment by lambui** [comment]
as discussed in #4, you should rise these issues in the [Community Mod Repo](https://github.com/Pathoschild/StardewCommunityMods) as I no longer actively work on this mod and can't really offer much help :(

**Comment by Pathoschild** [comment]
For reference, I'm already working on a fix for that in the community mod repo. :)
